### ISSUE TITLE
RegExp without flags throws error

### ISSUE THREAD

**Issue by cshaa** [jonschlinkert/shallow-clone#4] opened 2019-04-14 21:23 UTC
[Try it online.](https://repl.it/repls/ScalyVisibleCopyleft)

Code:
```typescript
const clone = require('shallow-clone');
console.log(clone(/a/));
```

Error:
```
SyntaxError: Invalid flags supplied to RegExp constructor 'null'
    at new RegExp (<anonymous>)
    at cloneRegExp (node_modules/shallow-clone/index.js:52:14)
```

**Comment by jonschlinkert** [comment] 2019-04-16 00:07
duplicate of https://github.com/jonschlinkert/shallow-clone/pull/3. This has been fixed.

**Closed as completed by jonschlinkert** 2019-04-16 00:07 UTC
